include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - 'build/**'
  errors:
    avoid_catches_without_on_clauses: ignore

linter:
  rules:
    document_ignores: false
    public_member_api_docs: false
