import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:dcli/dcli.dart';
import 'package:in_phase/src/database/database.exports.dart';
import 'package:in_phase/src/library/library.dart';
import 'package:in_phase/src/logger/logger.dart';
import 'package:in_phase/src/misc/misc.dart';
import 'package:in_phase/src/spotify/spotify.dart';
import 'package:io/io.dart';
import 'package:path/path.dart' as p;
import 'package:rekorddart/rekorddart.dart';

/// Writes `in-phase-data.js` for the spicetify-in-phase extension.
class ExportSpicetifyCommand extends Command<int> {
  ExportSpicetifyCommand() {
    argParser.addOption(
      'output',
      abbr: 'o',
      help:
          'Output path for in-phase-data.js '
          '(default: ~/.config/spicetify/Extensions/in-phase-data.js).',
    );
  }

  @override
  final String name = 'spicetify';

  @override
  final String description =
      'Export Spotify track id → Rekordbox key + BPM as in-phase-data.js '
      'for the spicetify-in-phase extension.';

  @override
  Future<int> run() async {
    final outputPath = _resolveOutputPath();

    return withTeardown((addTeardown) async {
      final rbDb = await RekordboxDatabase.connect(
        allowConnectionWhenRunning: true,
      );
      addTeardown(rbDb.close);

      final mappings = await db().syncMappingsDao.getAllMappings();
      final rbMeta = await loadRekordboxSongMeta(rbDb);

      final trackEntries = <_SpicetifyTrackEntry>[];
      var skippedNoMeta = 0;

      for (final MapEntry(key: spotifyTrackId, value: rbSongId)
          in mappings.entries) {
        final meta = rbMeta[rbSongId];
        if (meta == null || !meta.hasMetadata) {
          skippedNoMeta++;
          continue;
        }

        final camelot = mapKeyToCamelot(meta.keyName);
        final camelotKey = camelot != null
            ? CamelotKey.fromString(camelot)
            : null;

        if (camelotKey == null && meta.bpm == null) {
          skippedNoMeta++;
          continue;
        }

        trackEntries.add(
          _SpicetifyTrackEntry(
            trackId: spotifyTrackId,
            camelotKey: camelotKey,
            bpm: meta.bpm,
          ),
        );
      }

      final js = _generateInPhaseDataJs(trackEntries);
      final outFile = File(outputPath);
      outFile.parent.createSync(recursive: true);
      outFile.writeAsStringSync(js);

      log
        ..info('Wrote ${green(outputPath)}')
        ..info(
          'Tracks: ${trackEntries.length} with metadata · '
          '$skippedNoMeta mapped without usable key/BPM · '
          '${mappings.length} total Spotify↔RB mappings',
        );

      if (trackEntries.isEmpty) {
        log.warning(
          'No tracks exported. Run `in_phase sync` and ensure Rekordbox '
          'tracks have key/BPM analysis.',
        );
      }

      return ExitCode.success.code;
    });
  }

  String _resolveOutputPath() {
    final override = argResults!['output'] as String?;
    if (override != null && override.trim().isNotEmpty) {
      return p.normalize(override);
    }

    final configHome =
        Platform.environment['SPICETIFY_CONFIG'] ??
        p.join(
          Platform.environment['HOME'] ??
              Platform.environment['USERPROFILE'] ??
              '.',
          '.config',
          'spicetify',
        );
    return p.join(configHome, 'Extensions', 'in-phase-data.js');
  }
}

class _SpicetifyTrackEntry {
  const _SpicetifyTrackEntry({
    required this.trackId,
    required this.camelotKey,
    required this.bpm,
  });

  final SpotifyTrackId trackId;
  final CamelotKey? camelotKey;
  final int? bpm;
}

String _generateInPhaseDataJs(List<_SpicetifyTrackEntry> entries) {
  final keysObject = StringBuffer()..writeln('var Keys = Object.freeze({');
  for (final key in CamelotKey.values) {
    keysObject.writeln('  ${key.name}: "${key.title}",');
  }
  keysObject.writeln('});');

  final tracksObject = StringBuffer()
    ..writeln('globalThis.__inPhaseTracks = {');
  for (final entry in entries) {
    final fields = <String>[];
    if (entry.camelotKey != null) {
      fields.add('key: Keys.${entry.camelotKey!.name}');
    }
    if (entry.bpm != null) {
      fields.add('bpm: ${entry.bpm}');
    }
    tracksObject.writeln('  "${entry.trackId}": { ${fields.join(', ')} },');
  }
  tracksObject.writeln('};');

  return '''
// Generated by in_phase export spicetify — do not edit
$keysObject
$tracksObject
''';
}
